name: Build Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-windows:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              name: "Windows Server 2019 / Qt 5",
              os: windows-2019,
              qt_modules: "qtwebengine",
              qt_version: "5.9.9",
              configurePreset: "ninja-multi-vcpkg",
              buildPreset: "ninja-multi-vcpkg-release",
              publishArtifacts: true
            }
          - {
              name: "Windows Server 2019 / Qt 5 / Portable",
              os: windows-2019,
              qt_modules: "qtwebengine",
              qt_version: "5.9.9",
              configurePreset: ninja-multi-vcpkg-portable,
              buildPreset: ninja-multi-vcpkg-portable-release,
              publishArtifacts: true
            }

    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows-release

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: ${{ runner.workspace }}/vcpkg
          vcpkgGitCommitId: fba75d09065fcc76a25dcf386b1d00d33f5175af # 2024.02.14

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          modules: ${{ matrix.config.qt_modules }}
          version: ${{ matrix.config.qt_version }}
          cache: true
          extra: --external 7z

      - name: Configure & Build
        uses: lukka/run-cmake@v10
        with:
          configurePreset: ${{ matrix.config.configurePreset }}
          buildPreset: ${{ matrix.config.buildPreset }}

      - name: Retrieve Application Version
        run: |
          $zeal_version = Get-Content build/${{ matrix.config.configurePreset }}/zeal_version
          Write-Output "Zeal Version: $zeal_version"
          "ZEAL_VERSION=$zeal_version" >> $env:GITHUB_ENV

      - name: Package
        if: matrix.config.publishArtifacts
        run: cmake --build build --preset ${{ matrix.config.buildPreset }} --target package
        env:
          CODESIGN_CERTIFICATE_BASE64: ${{ secrets.CODESIGN_CERTIFICATE_BASE64 }}
          CODESIGN_PASSWORD: ${{ secrets.CODESIGN_PASSWORD }}

      - name: Upload ZIP Artifacts
        if: matrix.config.publishArtifacts
        uses: actions/upload-artifact@v4
        with:
          name: zeal-${{ env.ZEAL_VERSION }}${{ matrix.config.configurePreset == 'ninja-multi-vcpkg-portable' &&  '-portable' || '' }}-windows-x64.zip
          path: |
            build/${{ matrix.config.configurePreset }}/zeal-*.zip
            build/${{ matrix.config.configurePreset }}/zeal-*.zip.sha256

      - name: Upload MSI Artifacts
        if: matrix.config.publishArtifacts && matrix.config.configurePreset == 'ninja-multi-vcpkg'
        uses: actions/upload-artifact@v4
        with:
          name: zeal-${{ env.ZEAL_VERSION }}-windows-x64.msi
          path: |
            build/${{ matrix.config.configurePreset }}/zeal-*.msi
            build/${{ matrix.config.configurePreset }}/zeal-*.msi.sha256
